---
- name: Ensure application directory exists
  ansible.builtin.file:
    path: /opt/apps
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure Ansible sudo access
  ansible.builtin.import_tasks: sudo.yml
