---
- name: Check Raspberry Pi Server
  hosts: raspberry_pi
  gather_facts: true

  tasks:
    - name: Show hostname
      ansible.builtin.debug:
        msg: "{{ ansible_facts['hostname'] }}"

    - name: Show operating system
      ansible.builtin.debug:
        msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"

    - name: Show architecture
      ansible.builtin.debug:
        msg: "{{ ansible_facts['architecture'] }}"

    - name: Show available memory
      ansible.builtin.debug:
        msg: "{{ ansible_facts['memfree_mb'] }} MB free"

    - name: Show total memory
      ansible.builtin.debug:
        msg: "{{ ansible_facts['memtotal_mb'] }} MB total"

    - name: Show memory
      ansible.builtin.debug:
        var: ansible_facts['memory_mb']
